### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by sandlerben** [hack4impact/audio-transcription-service#13]
A few options
- transcriber
- ats
- scribe
- scribbly
- pimp my scriber
- speecher
- textify

**Comment by sandlerben** [comment]
@anoshaminai @roornelas @yoninachmany @rachelhongca

**Comment by yoninachmany** [comment]
- speech.txt
- when2scribe
- scribe4me

**Comment by anoshaminai** [comment]
scribscrabscruble
autoscribe
autoscript
scribe.me
sound 2 text
text.me
audiocrawl

**Comment by sandlerben** [comment]
Let's vote this Saturday.

**Comment by yoninachmany** [comment]
@sandlerben we forgot to vote on this

**Comment by sandlerben** [comment]
Yes, we did forget. There is no rush so we can vote next time we meet.

## 

Benjamin Sandler
University of Pennsylvania | Class of 2018
Candidate for BS in Computer Science & BA in Cognitive Science
954.478.6689 | ben1sandler@gmail.com

**Comment by roornelas** [comment]
scribeDaH8ers

**Comment by yoninachmany** [comment]
Top 4:
sound2text
Transcribe4All
speech.txt
audioscrawl
